### PR TITLE
v1.1.0 - Add new icons

### PR DESCRIPTION
**Pull request by x1unix**

### CODE REVIEW

**Review by bdoorr — CHANGES_REQUESTED** [review]
Please share this icon

**Review by bdoorr — CHANGES_REQUESTED** [review]
Please share me icon.. thanks for your

**Comment by x1unix** [comment]
Hello @bdoorr. Unfortunately I lost a sign key for APK so I’m unable to share an update on Google Play.

I can recommend you to do a fork of this repo and publish it as a new on Google Play, or built it yourself locally with Android Studio

**Comment by ildar** [comment]
FYI AFAIK the app is published in F-Droid.

**Comment by x1unix** [comment]
@ildar idk who posted an actual APK build there and who maintains it.

**Comment by ildar** [comment]
it is kinda independent from an original author / usually no action needed.
Though it's usually required that the author approves package presence in
F-Droid.

**Comment by x1unix** [comment]
@ildar I remember that I've requested to add my package, but explicitly didn't add any apk file. afaik they rebuild and resign it with own custom keys, but don't know how this process goes.

**Pull request merged**
